name: pdft
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  syncfusion_flutter_pdf: ^23.1.41
  flutter:
    sdk: flutter
  pdfx: ^2.4.0
  http: ^1.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ANGSAI
      fonts:
        - asset:  src/font/ANGSA.ttf
 
 
 